# .github/workflows/nuget-publish.yml

name: Publish NuGet Package

on:
  workflow_dispatch:
    inputs:
      project_path:
        description: Path to the library .csproj
        required: false
        default: src/R3sult4Net/R3sult4Net.csproj
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ${{ inputs.project_path || 'src/R3sult4Net/R3sult4Net.csproj' }}
      CONFIGURATION: Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files
        run: ls -R

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c ${{ env.CONFIGURATION }}

      - name: Test
        run: dotnet test --no-build -c ${{ env.CONFIGURATION }} --verbosity normal -l "console;verbosity=detailed"

      - name: Pack (no tag)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          dotnet pack "${{ env.PROJECT_PATH }}" \
            --configuration "${{ env.CONFIGURATION }}" \
            --no-build \
            --output ./nupkg

      - name: Pack (tagged release)
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          # Extract version from tag (strip leading 'v')
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Packing version $VERSION from tag $GITHUB_REF_NAME"
          dotnet pack "${{ env.PROJECT_PATH }}" \
            --configuration "${{ env.CONFIGURATION }}" \
            --no-build \
            /p:PackageVersion="$VERSION" \
            --output ./nupkg

      - name: Push NuGet Package
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
